server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: pdpj2022
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'